create table members (
    id int primary key generated by default as identity,
    first_name varchar(50) default null,
    last_name varchar(50) default null,
    email varchar(255) not null,
    country varchar(255) default null,
    created timestamp default current_timestamp,
    status smallint null default '1'
);